site_name: HPCAdvisor
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences
theme:
  name: material
  icon:
    logo: material/atom
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      primary: indigo
      accent: indigo
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: indigo
      accent: indigo
plugins:
  - search
repo_url: https://github.com/Azure/hpcadvisor
extra:
  generator: false
copyright: |
  &copy; Copyright 2024, Microsoft
nav:
  - HPCAdvisor: index.md
  - Quickstart: quickstart.md
  - Examples: examples.md
  - Configuration Files: configfiles.md
  - Commands: commands.md
